export const quotePage = {
  hero: {
    title: 'Request a Technical Quote',
    description:
      'Engage with our engineering team for precision manufacturing and turnkey solutions. Backed by ISO 9001:2015 certification, we deliver authoritative industrial excellence.',
  },
  steps: [
    { number: 1, shortLabel: 'Contact', label: 'Contact Information' },
    { number: 2, shortLabel: 'Details', label: 'Product Details' },
    { number: 3, shortLabel: 'Specs', label: 'Technical Specifications' },
  ],
  successMessage:
    'Thank you. Your quote request has been submitted. Our engineering team will respond within 24–48 business hours.',
} as const

export const productCategories = [
  { value: 'distribution-transformers', label: 'Distribution Transformers' },
  { value: 'turnkey-projects', label: 'Turnkey Projects' },
  { value: 'maintenance-retrofitting', label: 'Maintenance & Retrofitting' },
] as const

export const transformerTypes = [
  { value: '', label: 'Select equipment class...' },
  { value: 'distribution', label: 'Distribution Transformer' },
  { value: 'power', label: 'Power Transformer' },
  { value: 'specialty', label: 'Specialty / Custom Build' },
] as const

export const coolingTypes = [
  { value: '', label: 'Select cooling method...' },
  { value: 'onan', label: 'ONAN (Oil Natural Air Natural)' },
  { value: 'onaf', label: 'ONAF (Oil Natural Air Forced)' },
  { value: 'ofaf', label: 'OFAF (Oil Forced Air Forced)' },
] as const

export const windingMaterials = [
  { value: 'copper', label: 'Electrolytic Copper' },
  { value: 'aluminum', label: 'High-Grade Aluminum' },
] as const

export const complianceStandards = [
  {
    id: 'standardsIs' as const,
    label: 'IS (Indian Standards)',
    description: 'Default requirement',
    defaultChecked: true,
  },
  {
    id: 'standardsIec' as const,
    label: 'IEC Standards',
    description: 'International Electrotechnical',
    defaultChecked: false,
  },
  {
    id: 'standardsAnsi' as const,
    label: 'ANSI Standards',
    description: 'American National',
    defaultChecked: false,
  },
] as const

export const quoteSidebar = {
  commitment: {
    title: 'Commitment',
    items: [
      {
        title: 'Technical Support Grid',
        description:
          'Dedicated engineering team assigned to evaluate your specific load requirements.',
      },
      {
        title: 'On-Site Evaluation',
        description:
          'Option for preliminary site assessment for complex turnkey projects.',
      },
      {
        title: 'Fast-Track Processing',
        description:
          'Comprehensive quote delivery within 24-48 hours of complete specification submission.',
      },
    ],
  },
  precision: {
    title: 'Our Commitment to Precision',
    description:
      'Every quote generated by Tejaswini Industries is backed by our rigorous engineering standards. Our components are machined to exact tolerances, ensuring unparalleled reliability in high-stress industrial environments.',
    bullets: ['100% Quality Assurance', 'Adherence to IEC Standards'],
  },
} as const
